trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t First-set.azurecr.io/web-game:tag 2048-game
      az acr login -n First-set
      docker push First-set.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'toazportal'
    azureResourceGroup: 'First-set'
    kubernetesCluster: 'First-AKS'
    namespace: 'default'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'toazportal'
    azureContainerRegistry: 'firstcontainer.azurecr.io'
    forceUpdate: false
